HOME=.
LIB=../../f90/lib
XDRLIB=$(LIB)/external/xdr-interface-fortran/xdrfile-1.1.4/lib
XDRINTERFACE=$(LIB)/external/xdr-interface-fortran
NCLIB=$(LIB)/external/netcdf/netcdf/lib
NCINC=$(LIB)/external/netcdf/netcdf/include
EXEF=catcrd
TRGT=catcrd

# Select Fortran compiler
#
chk_ifort := $(shell which ifort    >/dev/null 2>&1 && echo 1 || echo 0)
chk_ifx   := $(shell which ifx      >/dev/null 2>&1 && echo 1 || echo 0)
chk_gfort := $(shell which gfortran >/dev/null 2>&1 && echo 1 || echo 0)


ifeq ($(FC),ifort)
	FFLAGS = -qopenmp
else ifeq ($(FC),ifx)
	FFLAGS = -qopenmp
else ifeq ($(FC),gfortran)
	FFLAGS = -fopenmp
else
	ifeq ($(chk_ifort),1)
		FC     = ifort
		FFLAGS = -qopenmp
	else ifeq ($(chk_ifx),1)
		FC     = ifx
		FFLAGS = -qopenmp
	else ifeq ($(chk_gfort),1)
		FC     = gfortran
		FFLAGS = -fopenmp
	endif
endif

# Source codes
#
OBJ=${XDRINTERFACE}/xdr.F90      \
    ${LIB}/util.f90              \
    ${LIB}/const.f90             \
    $(LIB)/netcdf.f90            \
    ${LIB}/dcd.f90               \
    ${LIB}/xtclib.f90            \
    ${LIB}/traj.f90              \
    ${HOME}/parse_arguments.f90  \
    ${HOME}/catcrd_ctrl.f90      \
    ${HOME}/catcrd_analyze.f90   \
    ${HOME}/catcrd.f90

$(TRGT) : $(OBJ) 
	$(FC) $(FFLAGS) -o $(EXEF) $(OBJ) -L $(XDRLIB) -lxdrfile -L $(NCLIB) -I $(NCINC) -lnetcdf -lnetcdff
	mkdir -p ../../bin
	cp $(EXEF) ../../bin/
	rm -f *.mod
